blank_issues_enabled: false
contact_links:
    - name: New Feature request
      url: https://github.com/hhftechnology/Dock-Dploy/discussions/new?category=request-feature
      about: For feature/script requests, please use the Discussions section.
    - name: ðŸ¤” Questions and Help
      url: https://forum.hhf.technology/c/help/85
      about: For suggestions or questions, please use the Our forums.
    - name: Discord
      url: https://discord.gg/HDCt9MjyMJ
      about: Join our Discord server to chat with other users in the hhf community.