[variables]
main_domain = "${domain}"
redis_port = "6379"
redis_insight_port = "8001"
redis_password = "${redis_password}"

[config]
[[config.domains]]
serviceName = "redis_insight"
port = 8001
host = "${main_domain}"
path = "/redis"

[config.env]
REDIS_PORT = "${redis_port}"
REDIS_INSIGHT_PORT = "${redis_insight_port}"
REDIS_PASSWORD = "${redis_password}"

